modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="polars_mad_tweaks"
version="${file.jarVersion}"
displayName="Polar's Mad Tweaks"
logoFile="mad_tweaks.png"
authors="Polarice3"
description='''A bunch of tweaks added to vanilla mobs to be more logical to my silly brain.'''
[[dependencies.polars_mad_tweaks]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.polars_mad_tweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
